import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { toPascalCase } from './converter.js';
import type { AcfFieldGroup } from './types.js';

function fragmentName(group: AcfFieldGroup): string {
  return toPascalCase(group.graphql_field_name) + 'Fields';
}

function fragmentType(group: AcfFieldGroup): string {
  const type = group.graphql_types?.[0];
  if (!type) {
    console.warn(
      `  warning: ${group.title} has no graphql_types — defaulting to "Node". Set graphql_types in ACF or override in config.`
    );

    return 'Node';
  }

  return type;
}

function renderGraphQLFragment(group: AcfFieldGroup, fragment: string): string {
  const name = fragmentName(group);
  const type = fragmentType(group);

  return `# ${group.title} (auto-generated by acf-json-to-graphql)\nfragment ${name} on ${type} {\n${fragment}\n}\n`;
}

export async function writeFragments(
  groups: AcfFieldGroup[],
  fragments: Map<string, string>,
  outDir: string
): Promise<void> {
  await mkdir(outDir, { recursive: true });

  for (const group of groups) {
    const fragment = fragments.get(group.key);
    if (!fragment) continue;
    const content = renderGraphQLFragment(group, fragment);
    const outPath = join(outDir, `${group.graphql_field_name}.graphql`);
    await writeFile(outPath, content, 'utf-8');
    console.log(`  wrote ${outPath}`);
  }
}

export function printFragments(
  groups: AcfFieldGroup[],
  fragments: Map<string, string>
): void {
  for (const group of groups) {
    const fragment = fragments.get(group.key);
    if (!fragment) continue;
    console.log(renderGraphQLFragment(group, fragment));
  }
}
